sudo: required

dist: bionic

language: cpp

cache: ccache

jobs:
  include:
  - os: linux
    compiler: gcc

install:
  - g++ --version
  
script:
  - ./build.sh
  - make check

notifications:
  on_success: change
  on_failure: always
